### ISSUE TITLE
卡牌的上场

### ISSUE THREAD

**Issue by liangzilixueha** [liangzilixueha/Legends-of-Diana#12]
你需要
1.每更换一次回合，法力水晶绘制的数量+1（data/img/img_discord/power.png）
2.己方应该有三个链表（现在只有两个）
-》CardinFight战斗中
-》CardinHand手牌
-》CardinHouse在库中（未实现）
3.每点击一次回合，自动从库（无需从库中删除）中随机抽取一张到手牌中
4.手牌的位置位于整个视图的下方，规范位置
5.可以从手牌上场到战斗卡牌中

**Comment by Eanya-Tonic** [comment]
已完成，顺便重构了代码
除目前手牌无法拖动外，暂无其他问题
